name: OpenAIWhisper
channels:
  - conda-forge
dependencies:
  - ffmpeg
  - python=3.10
  - pip
  - ipython
  - jupyter
  - git-lfs
  - neovim
  - numpy
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/nightly/cu117
    - --pre torch[dynamo]
    - torchvision
    - torchaudio
    - git+https://github.com/huggingface/transformers
    - git+https://github.com/huggingface/datasets
    - librosa
    - jiwer
    - evaluate>=0.3.0
    - more-itertools
    - tensorboard