name: OpenAIWhisper
channels:
  - conda-forge
dependencies:
  - ffmpeg
  - python
  - pip
  - ipython
  - jupyter
  - git-lfs
  - pip:
    - torch>=1.7
    - torchaudio
    - git+https://github.com/huggingface/transformers
    - git+https://github.com/huggingface/datasets
    - librosa
    - jiwer
    - evaluate>=0.3.0
    - more-itertools
    - tensorboard